fix incorrect handling of RestEndpointIOException in ListenerUtils
reportportal/client-java-core pull request #1
Opened 2016-10-09 13:54 UTC by dmikhievich

2016-10-10 11:57 UTC, avarabyeu requested changes

2016-10-10 11:57 UTC, avarabyeu commented on src/main/java/com/epam/reportportal/listeners/ListenersUtils.java
> +		if (ReportPortalException.class.isInstance(exception) || RestEndpointIOException.class.equals(exception.getClass())) {
Agreed

2016-10-10 11:57 UTC, avarabyeu commented on src/test/java/com/epam/reportportal/listeners/ListenerUtilsTest.java
> +	public void handleException_restEndpointIOExceptionAndNullLogger() {
Do we really need this tests? What if logger is configured for files instead for system console?

2016-10-10 14:08 UTC, dmikhievich commented on src/test/java/com/epam/reportportal/listeners/ListenerUtilsTest.java
> +	public void handleException_restEndpointIOExceptionAndNullLogger() {
Basically this test checks the case when the "logger" method argument is null just to be sure that the error messaging code is reachable:
```
if (logger != null) {
       logger.error(message, exception);
} else {
       System.out.println(exception.getMessage());
}
```
And I agree that it makes sense to cover the code branch with output to logger too.

2016-10-10 15:30 UTC, dmikhievich commented on src/test/java/com/epam/reportportal/listeners/ListenerUtilsTest.java
> +	public void handleException_restEndpointIOExceptionAndNullLogger() {
Additional test was added.

2016-11-10 18:35 UTC, avarabyeu approved these changes

2016-11-10 18:35 UTC, merged